# Generated by Django 4.1.5 on 2023-05-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('image', models.ImageField(upload_to='imgbathroom/')),
            ],
        ),
        migrations.CreateModel(
            name='bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('image', models.ImageField(upload_to='imgbedroom/')),
            ],
        ),
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('image', models.ImageField(upload_to='imgkitchen/')),
            ],
        ),
        migrations.CreateModel(
            name='livingroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('image', models.ImageField(upload_to='imglivingroom/')),
            ],
        ),
        migrations.CreateModel(
            name='wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('days', models.IntegerField()),
                ('image', models.ImageField(upload_to='imgwardrobe/')),
            ],
        ),
    ]
